### ISSUE TITLE
Error with the http://localhost:3000/admin API

### ISSUE THREAD

**Issue by abhi18av** [wwiill/jwe-auth#3]
Hi @wwiill ,

I did run into another issue here :)

This one is with the admin API which ought to be validated once the authentication token has been generated but here's the current status

- Login API

```sh
> http --json POST 'http://localhost:3000/login' \
    'Content-Type':'application/json; charset=utf-8' \
    username="admin" \
    password="secret"


{:token "eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMTI4R0NNIn0.5UXVDm3B2CrFtsPmgrSBKecuZAcM-vEd.VagjY3frDJsFPBhz.Aiis6PGejMXMlTMPaql-bONezg0HjETfMNSCT7opi-8z.bG7tSOTMoWaDgBqsazOBVw"}
```

- Admin API

But when I try to use this token in the admin API, I send the request containing the `Authorization` header it fails 

```

> http --json GET 'http://localhost:3000/admin' \
    'Authorization':'eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMTI4R0NNIn0.5UXVDm3B2CrFtsPmgrSBKecuZAcM-vEd.VagjY3frDJsFPBhz.Aiis6PGejMXMlTMPaql-bONezg0HjETfMNSCT7opi-8z.bG7tSOTMoWaDgBqsazOBVw' \
    'Content-Type':'application/json; charset=utf-8'

{:msg "Not allowed"}

```

Am I doing something wrong here ?

**Comment by wwiill** [comment]
You are missing the TOKEN xxx bit.

**Comment by abhi18av** [comment]
Yup, completely resolved now.

Thanks once again @wwiill 👍
